openapi: 3.0.0
info:
  title: Project Verena Weikert API
  version: 1.0.0
  description: Aplicação CRUD para gerenciamento de usuários

servers:
  - url: http://localhost:8081
    description: Servidor local

paths:
  /users:
    get:
      summary: Retorna a lista de todos os usuários
      tags:
        - Users
      responses:
        "200":
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Cria um novo usuário
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: O usuário foi criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          description: Erro no servidor

  /users/{id}:
    put:
      summary: Atualiza um usuário existente
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: O usuário foi atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Usuário não encontrado
        "500":
          description: Erro no servidor

    delete:
      summary: Remove um usuário existente
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: O usuário foi removido com sucesso
        "404":
          description: Usuário não encontrado
        "500":
          description: Erro no servidor

components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
          description: O ID do usuário
        name:
          type: string
          description: O nome do usuário
        email:
          type: string
          description: O email do usuário
      example:
        id: 1
        name: João Silva
        email: silva.joao@email.com
